import { useState, useRef } from 'react';
import { jsPDF } from 'jspdf';

// Helper to export CSV/Excel format
const downloadCsv = (_title: string, headers: string[], rows: any[][], filename: string) => {
  const csvContent =
    'data:text/csv;charset=utf-8,' +
    [headers.join(','), ...rows.map((r) => r.map((val) => `"${String(val).replace(/"/g, '""')}"`).join(','))].join('\n');
  const encodedUri = encodeURI(csvContent);
  const link = document.createElement('a');
  link.setAttribute('href', encodedUri);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Helper to export beautifully formatted PDF Report
const downloadPdfReport = (
  reportTitle: string,
  headers: string[],
  rows: any[][],
  filename: string,
  summaryCards: { label: string; value: string }[],
) => {
  const doc = new jsPDF();

  // Primary Theme Color: Emerald Green (16, 185, 129)
  // Background/Slate Theme Color: (15, 23, 42)

  // Header Banner
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 40, 'F');

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(16, 185, 129); // Emerald Green
  doc.text('OCCASIO ANALYTICS', 15, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(148, 163, 184); // Slate 400
  doc.text('Platform Performance & Revenue Report', 15, 26);

  // Generate Date/Time
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // Slate 500
  doc.text(`Report Date: ${new Date().toLocaleString()}`, 130, 26);

  // Section: Overview
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 41, 59); // Slate 800
  doc.text(reportTitle, 15, 52);

  // Draw Summary Cards
  let cardX = 15;
  const cardWidth = (210 - 30 - (summaryCards.length - 1) * 8) / summaryCards.length;
  
  summaryCards.forEach((card) => {
    // Card background
    doc.setFillColor(241, 245, 249); // slate 100
    doc.rect(cardX, 60, cardWidth, 22, 'F');
    
    // Left border (Emerald accent)
    doc.setFillColor(16, 185, 129);
    doc.rect(cardX, 60, 3, 22, 'F');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139); // slate 500
    doc.text(card.label.toUpperCase(), cardX + 6, 68);

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42); // slate 900
    doc.text(card.value, cardX + 6, 76);

    cardX += cardWidth + 8;
  });

  // Section: Data Table
  let currentY = 96;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text('Tabular Details', 15, currentY);
  currentY += 6;

  // Table Headers
  doc.setFillColor(15, 23, 42); // Dark slate header
  doc.rect(15, currentY, 180, 8, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);

  const colWidth = 180 / headers.length;
  headers.forEach((header, idx) => {
    doc.text(header, 17 + idx * colWidth, currentY + 5.5);
  });

  currentY += 8;

  // Table Rows
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85); // slate 700

  rows.forEach((row, rowIdx) => {
    // Alternating Row Background
    if (rowIdx % 2 === 1) {
      doc.setFillColor(248, 250, 252); // slate 50
      doc.rect(15, currentY, 180, 8, 'F');
    }

    row.forEach((cell, cellIdx) => {
      doc.text(String(cell), 17 + cellIdx * colWidth, currentY + 5.5);
    });

    // Row separator
    doc.setDrawColor(241, 245, 249);
    doc.line(15, currentY + 8, 195, currentY + 8);

    currentY += 8;
  });

  // Footer Accent
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text('Generated by Occasio Dashboard Core. All rights reserved.', 15, 285);

  doc.save(filename);
};

// ==========================================
// ADMIN DASHBOARD CHARTS COMPONENT
// ==========================================
interface AdminChartProps {
  trend: {
    year?: number;
    month?: number;
    label: string;
    subscription: number;
    publishing: number;
    commission: number;
    total: number;
    users: number;
    managers: number;
  }[];
}

export const AdminDashboardCharts = ({ trend }: AdminChartProps) => {
  const [activeSeries, setActiveSeries] = useState({
    subscription: true,
    publishing: true,
    commission: true,
    total: true,
  });

  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  if (!trend || trend.length === 0) return null;

  // Find max value for scaling financial chart
  const seriesKeys = Object.keys(activeSeries) as ('subscription' | 'publishing' | 'commission' | 'total')[];
  const maxVal = Math.max(
    ...trend.map((d) =>
      Math.max(...seriesKeys.map((k) => (activeSeries[k] ? d[k] : 0)))
    ),
    100
  );

  // Scaling helper values for SVG Line Chart
  const width = 600;
  const height = 280;
  const paddingLeft = 60;
  const paddingRight = 20;
  const paddingTop = 30;
  const paddingBottom = 40;
  const graphWidth = width - paddingLeft - paddingRight;
  const graphHeight = height - paddingTop - paddingBottom;

  const getCoordinates = (index: number, val: number) => {
    const x = paddingLeft + (index / (trend.length - 1)) * graphWidth;
    const y = paddingTop + graphHeight - (val / maxVal) * graphHeight;
    return { x, y };
  };

  // Generate SVG Path for a series
  const getPathData = (key: 'subscription' | 'publishing' | 'commission' | 'total') => {
    return trend
      .map((d, i) => {
        const { x, y } = getCoordinates(i, d[key]);
        return `${i === 0 ? 'M' : 'L'} ${x} ${y}`;
      })
      .join(' ');
  };

  // Generate SVG Area Path for total gradient
  const getAreaPathData = () => {
    const linePath = trend
      .map((d, i) => {
        const { x, y } = getCoordinates(i, d.total);
        return `L ${x} ${y}`;
      })
      .join(' ');

    const start = getCoordinates(0, 0);
    const end = getCoordinates(trend.length - 1, 0);
    return `M ${start.x} ${start.y} ${linePath} L ${end.x} ${end.y} Z`;
  };

  // Handle Export Functions
  const handleExportCsv = () => {
    const headers = ['Month', 'Subscription Rev (INR)', 'Publishing Rev (INR)', 'Commission Rev (INR)', 'Total Rev (INR)', 'User Registrations', 'Manager Registrations'];
    const rows = trend.map((d) => [
      d.label,
      d.subscription,
      d.publishing,
      d.commission,
      d.total,
      d.users,
      d.managers,
    ]);
    downloadCsv('Admin Dashboard Data', headers, rows, `admin-dashboard-stats-${new Date().toISOString().split('T')[0]}.csv`);
  };

  const handleExportPdf = () => {
    const headers = ['Month', 'Sub (₹)', 'Publish (₹)', 'Commission (₹)', 'Total (₹)', 'Users', 'Managers'];
    const rows = trend.map((d) => [
      d.label,
      `₹${d.subscription}`,
      `₹${d.publishing}`,
      `₹${d.commission}`,
      `₹${d.total}`,
      d.users,
      d.managers,
    ]);
    const totalRevAllTime = trend.reduce((sum, d) => sum + d.total, 0);
    const totalUsersAdded = trend.reduce((sum, d) => sum + d.users, 0);
    const totalManagersAdded = trend.reduce((sum, d) => sum + d.managers, 0);

    const summaryCards = [
      { label: 'Total Revenue (6m)', value: `₹${totalRevAllTime}` },
      { label: 'New Users (6m)', value: String(totalUsersAdded) },
      { label: 'New Managers (6m)', value: String(totalManagersAdded) },
    ];

    downloadPdfReport(
      'Admin Financial & Platform Overview',
      headers,
      rows,
      `admin-dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`,
      summaryCards
    );
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
      {/* Financial Line Chart */}
      <div className="lg:col-span-2 bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-3xl p-6 shadow-xl relative overflow-hidden flex flex-col">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 relative z-10">
          <div>
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <span>📈</span> Financial Performance
            </h3>
            <p className="text-xs text-slate-400 mt-1">Platform revenue breakdown over last 6 months</p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleExportCsv}
              className="px-3 py-1.5 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 text-xs font-semibold rounded-lg border border-emerald-500/20 transition-all flex items-center gap-1.5 cursor-pointer"
            >
              📥 CSV
            </button>
            <button
              onClick={handleExportPdf}
              className="px-3 py-1.5 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 text-xs font-semibold rounded-lg border border-indigo-500/20 transition-all flex items-center gap-1.5 cursor-pointer"
            >
              📄 PDF
            </button>
          </div>
        </div>

        {/* Chart Series Toggle Legends */}
        <div className="flex flex-wrap gap-4 mb-6 text-xs font-medium z-10">
          <label className="flex items-center gap-2 text-indigo-400 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={activeSeries.subscription}
              onChange={() => setActiveSeries({ ...activeSeries, subscription: !activeSeries.subscription })}
              className="accent-indigo-500 rounded"
            />
            Subscriptions
          </label>
          <label className="flex items-center gap-2 text-amber-400 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={activeSeries.publishing}
              onChange={() => setActiveSeries({ ...activeSeries, publishing: !activeSeries.publishing })}
              className="accent-amber-500 rounded"
            />
            Publish Fee
          </label>
          <label className="flex items-center gap-2 text-sky-400 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={activeSeries.commission}
              onChange={() => setActiveSeries({ ...activeSeries, commission: !activeSeries.commission })}
              className="accent-sky-500 rounded"
            />
            Commissions
          </label>
          <label className="flex items-center gap-2 text-emerald-400 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={activeSeries.total}
              onChange={() => setActiveSeries({ ...activeSeries, total: !activeSeries.total })}
              className="accent-emerald-500 rounded"
            />
            Total Revenue
          </label>
        </div>

        {/* SVG Drawing Canvas */}
        <div className="relative flex-1 min-h-[280px]" ref={containerRef}>
          <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full text-slate-500">
            {/* Gradients */}
            <defs>
              <linearGradient id="total-grad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#10b981" stopOpacity="0.15" />
                <stop offset="100%" stopColor="#10b981" stopOpacity="0.0" />
              </linearGradient>
            </defs>

            {/* Background Grid Lines */}
            {[0, 0.25, 0.5, 0.75, 1].map((ratio, i) => {
              const y = paddingTop + ratio * graphHeight;
              const val = Math.round(maxVal * (1 - ratio));
              return (
                <g key={i}>
                  <line
                    x1={paddingLeft}
                    y1={y}
                    x2={width - paddingRight}
                    y2={y}
                    stroke="currentColor"
                    strokeOpacity={0.08}
                    strokeDasharray="4 4"
                  />
                  <text
                    x={paddingLeft - 8}
                    y={y + 4}
                    textAnchor="end"
                    className="text-[9px] fill-slate-500 font-semibold"
                  >
                    ₹{val}
                  </text>
                </g>
              );
            })}

            {/* X-Axis labels */}
            {trend.map((d, i) => {
              const x = paddingLeft + (i / (trend.length - 1)) * graphWidth;
              return (
                <text
                  key={i}
                  x={x}
                  y={height - paddingBottom + 18}
                  textAnchor="middle"
                  className="text-[10px] fill-slate-400 font-bold"
                >
                  {d.label}
                </text>
              );
            })}

            {/* Total Area Gradient */}
            {activeSeries.total && (
              <path d={getAreaPathData()} fill="url(#total-grad)" />
            )}

            {/* Lines for active series */}
            {activeSeries.subscription && (
              <path
                d={getPathData('subscription')}
                fill="none"
                stroke="#6366f1"
                strokeWidth={2.5}
                strokeLinecap="round"
                className="transition-all duration-300"
              />
            )}
            {activeSeries.publishing && (
              <path
                d={getPathData('publishing')}
                fill="none"
                stroke="#f59e0b"
                strokeWidth={2.5}
                strokeLinecap="round"
                className="transition-all duration-300"
              />
            )}
            {activeSeries.commission && (
              <path
                d={getPathData('commission')}
                fill="none"
                stroke="#0ea5e9"
                strokeWidth={2.5}
                strokeLinecap="round"
                className="transition-all duration-300"
              />
            )}
            {activeSeries.total && (
              <path
                d={getPathData('total')}
                fill="none"
                stroke="#10b981"
                strokeWidth={3}
                strokeLinecap="round"
                className="transition-all duration-300"
              />
            )}

            {/* Hover Guides & Dots */}
            {trend.map((_, i) => {
              const x = paddingLeft + (i / (trend.length - 1)) * graphWidth;
              return (
                <rect
                  key={i}
                  x={x - graphWidth / (trend.length * 2)}
                  y={paddingTop}
                  width={graphWidth / (trend.length - 1)}
                  height={graphHeight}
                  fill="transparent"
                  className="cursor-crosshair"
                  onMouseEnter={() => setHoveredIdx(i)}
                  onMouseLeave={() => setHoveredIdx(null)}
                />
              );
            })}

            {/* Render Vertical line & points on hover */}
            {hoveredIdx !== null && (
              <g>
                <line
                  x1={getCoordinates(hoveredIdx, 0).x}
                  y1={paddingTop}
                  x2={getCoordinates(hoveredIdx, 0).x}
                  y2={height - paddingBottom}
                  stroke="#334155"
                  strokeWidth={1.5}
                  strokeDasharray="2 2"
                />
                {seriesKeys.map((key) => {
                  if (!activeSeries[key]) return null;
                  const { x, y } = getCoordinates(hoveredIdx, trend[hoveredIdx][key]);
                  const colorMap = {
                    subscription: '#6366f1',
                    publishing: '#f59e0b',
                    commission: '#0ea5e9',
                    total: '#10b981',
                  };
                  return (
                    <circle
                      key={key}
                      cx={x}
                      cy={y}
                      r={5}
                      fill={colorMap[key]}
                      stroke="#0f172a"
                      strokeWidth={2}
                    />
                  );
                })}
              </g>
            )}
          </svg>

          {/* Interactive HTML Tooltip inside SVG wrapper */}
          {hoveredIdx !== null && (
            <div
              className="absolute bg-slate-955 border border-slate-800 rounded-xl p-3 shadow-2xl pointer-events-none text-xs flex flex-col gap-1 z-20 text-slate-300"
              style={{
                left: `${getCoordinates(hoveredIdx, 0).x + 10}px`,
                top: `${paddingTop + 10}px`,
              }}
            >
              <p className="font-bold text-white mb-1 border-b border-slate-800 pb-1">
                {trend[hoveredIdx].label} {trend[hoveredIdx].year}
              </p>
              {activeSeries.subscription && (
                <p className="flex justify-between gap-4">
                  <span>Subscription:</span>
                  <span className="text-indigo-400 font-bold">₹{trend[hoveredIdx].subscription}</span>
                </p>
              )}
              {activeSeries.publishing && (
                <p className="flex justify-between gap-4">
                  <span>Publishing:</span>
                  <span className="text-amber-400 font-bold">₹{trend[hoveredIdx].publishing}</span>
                </p>
              )}
              {activeSeries.commission && (
                <p className="flex justify-between gap-4">
                  <span>Commissions:</span>
                  <span className="text-sky-400 font-bold">₹{trend[hoveredIdx].commission}</span>
                </p>
              )}
              {activeSeries.total && (
                <p className="flex justify-between gap-4 border-t border-slate-800/80 pt-1 font-semibold text-white">
                  <span>Total Rev:</span>
                  <span className="text-emerald-400">₹{trend[hoveredIdx].total}</span>
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* User & Manager Signups Growth Bar Chart */}
      <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-3xl p-6 shadow-xl flex flex-col">
        <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
          <span>👥</span> Account Growth
        </h3>
        <p className="text-xs text-slate-400 mb-6">User and Manager signups trend</p>

        <div className="flex-1 flex flex-col justify-between">
          <div className="flex flex-col gap-4">
            {trend.map((d, i) => {
              const maxUsers = Math.max(...trend.map((x) => x.users + x.managers), 1);
              const userPct = (d.users / maxUsers) * 100;
              const managerPct = (d.managers / maxUsers) * 100;

              return (
                <div key={i} className="flex items-center gap-3 text-xs">
                  <span className="w-8 text-slate-400 font-semibold">{d.label}</span>
                  <div className="flex-1 h-7 bg-slate-950/80 rounded-lg overflow-hidden flex border border-slate-800/50">
                    {d.users > 0 && (
                      <div
                        style={{ width: `${userPct}%` }}
                        className="bg-gradient-to-r from-emerald-600 to-emerald-400 h-full relative group flex items-center pl-2"
                        title={`${d.users} Users`}
                      >
                        <span className="text-[10px] text-emerald-950 font-extrabold">{d.users}</span>
                      </div>
                    )}
                    {d.managers > 0 && (
                      <div
                        style={{ width: `${managerPct}%` }}
                        className="bg-gradient-to-r from-indigo-600 to-indigo-400 h-full relative group flex items-center pl-2"
                        title={`${d.managers} Managers`}
                      >
                        <span className="text-[10px] text-indigo-950 font-extrabold">{d.managers}</span>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex justify-center gap-6 mt-6 text-xs font-semibold border-t border-slate-800/60 pt-4">
            <span className="flex items-center gap-2 text-emerald-400">
              <span className="w-3 h-3 rounded-full bg-emerald-400"></span> Users
            </span>
            <span className="flex items-center gap-2 text-indigo-400">
              <span className="w-3 h-3 rounded-full bg-indigo-400"></span> Managers
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};

// ==========================================
// MANAGER DASHBOARD CHARTS COMPONENT
// ==========================================
interface ManagerChartProps {
  trend: {
    label: string;
    revenue: number;
    bookingsCount: number;
  }[];
  eventDistribution: {
    eventId: string;
    title: string;
    revenue: number;
    ticketsSold: number;
  }[];
}

export const ManagerDashboardCharts = ({ trend, eventDistribution }: ManagerChartProps) => {
  const [hoveredIdx, setHoveredIdx] = useState<number | null>(null);
  const [chartType, setChartType] = useState<'revenue' | 'bookings'>('revenue');

  if (!trend || trend.length === 0) return null;

  const maxRevenue = Math.max(...trend.map((d) => d.revenue), 100);
  const maxBookings = Math.max(...trend.map((d) => d.bookingsCount), 10);

  const width = 600;
  const height = 280;
  const paddingLeft = 60;
  const paddingRight = 20;
  const paddingTop = 30;
  const paddingBottom = 40;
  const graphWidth = width - paddingLeft - paddingRight;
  const graphHeight = height - paddingTop - paddingBottom;

  const getCoordinates = (index: number, val: number, max: number) => {
    const x = paddingLeft + (index / (trend.length - 1)) * graphWidth;
    const y = paddingTop + graphHeight - (val / max) * graphHeight;
    return { x, y };
  };

  const getPathData = (key: 'revenue' | 'bookingsCount', max: number) => {
    return trend
      .map((d, i) => {
        const { x, y } = getCoordinates(i, d[key], max);
        return `${i === 0 ? 'M' : 'L'} ${x} ${y}`;
      })
      .join(' ');
  };

  const getAreaPathData = (key: 'revenue' | 'bookingsCount', max: number) => {
    const linePath = trend
      .map((d, i) => {
        const { x, y } = getCoordinates(i, d[key], max);
        return `L ${x} ${y}`;
      })
      .join(' ');

    const start = getCoordinates(0, 0, max);
    const end = getCoordinates(trend.length - 1, 0, max);
    return `M ${start.x} ${start.y} ${linePath} L ${end.x} ${end.y} Z`;
  };

  // Handle Export Functions
  const handleExportCsv = () => {
    const headers = ['Month', 'Organizer Revenue (INR)', 'Bookings Count'];
    const rows = trend.map((d) => [d.label, d.revenue, d.bookingsCount]);
    downloadCsv('Manager Performance Data', headers, rows, `manager-dashboard-stats-${new Date().toISOString().split('T')[0]}.csv`);
  };

  const handleExportPdf = () => {
    const headers = ['Month', 'Organizer Revenue (₹)', 'Bookings Count'];
    const rows = trend.map((d) => [d.label, `₹${d.revenue}`, d.bookingsCount]);

    const totalRevAllTime = trend.reduce((sum, d) => sum + d.revenue, 0);
    const totalBookingsAllTime = trend.reduce((sum, d) => sum + d.bookingsCount, 0);

    const summaryCards = [
      { label: 'Booking Revenue (6m)', value: `₹${totalRevAllTime}` },
      { label: 'Total Bookings (6m)', value: String(totalBookingsAllTime) },
    ];

    downloadPdfReport(
      'Event Manager Revenue & Bookings Overview',
      headers,
      rows,
      `manager-dashboard-report-${new Date().toISOString().split('T')[0]}.pdf`,
      summaryCards
    );
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-10">
      {/* Revenue & Bookings over time */}
      <div className="lg:col-span-2 bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-3xl p-6 shadow-xl relative overflow-hidden flex flex-col">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6 relative z-10">
          <div>
            <div className="flex items-center gap-3">
              <button
                onClick={() => setChartType('revenue')}
                className={`text-lg font-bold transition-all px-3 py-1 rounded-xl cursor-pointer ${
                  chartType === 'revenue' ? 'text-teal-400 bg-teal-500/10' : 'text-slate-400 hover:text-white'
                }`}
              >
                💰 Revenue Trend
              </button>
              <button
                onClick={() => setChartType('bookings')}
                className={`text-lg font-bold transition-all px-3 py-1 rounded-xl cursor-pointer ${
                  chartType === 'bookings' ? 'text-teal-400 bg-teal-500/10' : 'text-slate-400 hover:text-white'
                }`}
              >
                🎫 Bookings Trend
              </button>
            </div>
            <p className="text-xs text-slate-400 mt-1">Your store statistics over the last 6 months</p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={handleExportCsv}
              className="px-3 py-1.5 bg-teal-500/10 hover:bg-teal-500/20 text-teal-400 text-xs font-semibold rounded-lg border border-teal-500/20 transition-all flex items-center gap-1.5 cursor-pointer"
            >
              📥 CSV
            </button>
            <button
              onClick={handleExportPdf}
              className="px-3 py-1.5 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 text-xs font-semibold rounded-lg border border-indigo-500/20 transition-all flex items-center gap-1.5 cursor-pointer"
            >
              📄 PDF
            </button>
          </div>
        </div>

        {/* SVG Drawing Canvas */}
        <div className="relative flex-1 min-h-[280px]">
          <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-full text-slate-500">
            <defs>
              <linearGradient id="manager-grad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#14b8a6" stopOpacity="0.2" />
                <stop offset="100%" stopColor="#14b8a6" stopOpacity="0.0" />
              </linearGradient>
            </defs>

            {/* Background Grid Lines */}
            {[0, 0.25, 0.5, 0.75, 1].map((ratio, i) => {
              const y = paddingTop + ratio * graphHeight;
              const maxVal = chartType === 'revenue' ? maxRevenue : maxBookings;
              const val = Math.round(maxVal * (1 - ratio));
              return (
                <g key={i}>
                  <line
                    x1={paddingLeft}
                    y1={y}
                    x2={width - paddingRight}
                    y2={y}
                    stroke="currentColor"
                    strokeOpacity={0.08}
                    strokeDasharray="4 4"
                  />
                  <text
                    x={paddingLeft - 8}
                    y={y + 4}
                    textAnchor="end"
                    className="text-[9px] fill-slate-500 font-semibold"
                  >
                    {chartType === 'revenue' ? `₹${val}` : val}
                  </text>
                </g>
              );
            })}

            {/* X-Axis labels */}
            {trend.map((d, i) => {
              const x = paddingLeft + (i / (trend.length - 1)) * graphWidth;
              return (
                <text
                  key={i}
                  x={x}
                  y={height - paddingBottom + 18}
                  textAnchor="middle"
                  className="text-[10px] fill-slate-400 font-bold"
                >
                  {d.label}
                </text>
              );
            })}

            {/* Gradient fill */}
            <path
              d={getAreaPathData(
                chartType === 'revenue' ? 'revenue' : 'bookingsCount',
                chartType === 'revenue' ? maxRevenue : maxBookings
              )}
              fill="url(#manager-grad)"
            />

            {/* Line chart stroke */}
            <path
              d={getPathData(
                chartType === 'revenue' ? 'revenue' : 'bookingsCount',
                chartType === 'revenue' ? maxRevenue : maxBookings
              )}
              fill="none"
              stroke="#14b8a6"
              strokeWidth={3}
              strokeLinecap="round"
            />

            {/* Hover logic */}
            {trend.map((_, i) => {
              const x = paddingLeft + (i / (trend.length - 1)) * graphWidth;
              return (
                <rect
                  key={i}
                  x={x - graphWidth / (trend.length * 2)}
                  y={paddingTop}
                  width={graphWidth / (trend.length - 1)}
                  height={graphHeight}
                  fill="transparent"
                  className="cursor-crosshair"
                  onMouseEnter={() => setHoveredIdx(i)}
                  onMouseLeave={() => setHoveredIdx(null)}
                />
              );
            })}

            {hoveredIdx !== null && (
              <g>
                <line
                  x1={getCoordinates(hoveredIdx, 0, 1).x}
                  y1={paddingTop}
                  x2={getCoordinates(hoveredIdx, 0, 1).x}
                  y2={height - paddingBottom}
                  stroke="#334155"
                  strokeWidth={1.5}
                  strokeDasharray="2 2"
                />
                {(() => {
                  const val =
                    chartType === 'revenue'
                      ? trend[hoveredIdx].revenue
                      : trend[hoveredIdx].bookingsCount;
                  const max = chartType === 'revenue' ? maxRevenue : maxBookings;
                  const { x, y } = getCoordinates(hoveredIdx, val, max);
                  return (
                    <circle
                      cx={x}
                      cy={y}
                      r={6}
                      fill="#14b8a6"
                      stroke="#0f172a"
                      strokeWidth={2}
                    />
                  );
                })()}
              </g>
            )}
          </svg>

          {/* Floating Tooltip */}
          {hoveredIdx !== null && (
            <div
              className="absolute bg-slate-955 border border-slate-800 rounded-xl p-3 shadow-2xl pointer-events-none text-xs flex flex-col gap-1 z-20 text-slate-300"
              style={{
                left: `${getCoordinates(hoveredIdx, 0, 1).x + 10}px`,
                top: `${paddingTop + 10}px`,
              }}
            >
              <p className="font-bold text-white mb-1 border-b border-slate-800 pb-1">
                {trend[hoveredIdx].label}
              </p>
              <p className="flex justify-between gap-4">
                <span>Revenue:</span>
                <span className="text-teal-400 font-bold">₹{trend[hoveredIdx].revenue}</span>
              </p>
              <p className="flex justify-between gap-4">
                <span>Bookings:</span>
                <span className="text-teal-400 font-bold">{trend[hoveredIdx].bookingsCount}</span>
              </p>
            </div>
          )}
        </div>
      </div>

      {/* Event performance list (Horizontal Bar Chart) */}
      <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-3xl p-6 shadow-xl flex flex-col">
        <h3 className="text-lg font-bold text-white mb-1 flex items-center gap-2">
          <span>👑</span> Event Distribution
        </h3>
        <p className="text-xs text-slate-400 mb-6">Revenue and Tickets sold per event</p>

        {eventDistribution.length === 0 ? (
          <div className="flex-1 flex items-center justify-center text-slate-500 text-xs">
            No events with active booking revenue
          </div>
        ) : (
          <div className="flex-1 flex flex-col gap-4 overflow-y-auto max-h-[300px] pr-1">
            {eventDistribution.slice(0, 5).map((event, idx) => {
              const maxDistRevenue = Math.max(...eventDistribution.map((e) => e.revenue), 1);
              const percentage = (event.revenue / maxDistRevenue) * 100;
              return (
                <div key={idx} className="flex flex-col gap-1.5">
                  <div className="flex justify-between text-xs font-semibold">
                    <span className="text-slate-300 truncate w-32" title={event.title}>
                      {event.title}
                    </span>
                    <span className="text-teal-400">₹{event.revenue}</span>
                  </div>
                  <div className="w-full bg-slate-950 h-2.5 rounded-full overflow-hidden border border-slate-800/40">
                    <div
                      style={{ width: `${percentage}%` }}
                      className="bg-gradient-to-r from-teal-500 to-teal-300 h-full rounded-full"
                    ></div>
                  </div>
                  <div className="text-[10px] text-slate-500 flex justify-between">
                    <span>{event.ticketsSold} tickets sold</span>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
};
