export const ApiEndpoints = {
  Auth: {
    Base: '/api/auth',
    Signup: '/signup',
    VerifyOtp: '/verify-otp',
    ResendOtp: '/resend-otp',
    Me: '/me',
    ForgotPassword: '/forgot-password',
    Logout: '/logout',
    Refresh: '/refresh',
    Login: '/login',
    UpdatePassword: '/updatepassword',
    ResetPassword: '/reset-password',
    Google: '/google',
    GoogleCallback: '/google/callback',
    AdminLogin: '/admin/login',
  },
  User: {
    Base: '/api/user',
    UpgradeRole: '/upgraderole',
    Reapply: '/reapply',
    Profile: '/profile',
    Subscribe: '/subscribe',
    MySubscription: '/my-subscription',
  },
  Admin: {
    Base: '/api/admin',
    Users: '/users',
    BlockOrUnblock: '/blockorunblock/:userId',
    UserDetails: '/userDetails/:userId',
    PendingManagers: '/pendingmanagers/:userId',
    Approval: '/approval/:id',
    Rejection: '/rejection/:id',
    ManagerDetails: '/managerDetails/:id',
    Payments: '/payments',
    DashboardStats: '/dashboard-stats',
  },
  Events: {
    Base: '/api/events',
    Creation: '/creation',
    Events: '/events',
    EventDetails: '/eventDetails/:id',
    AllEvents: '/allevents',
    MyEvents: '/myevents',
    Update: '/update/:id',
    Delete: '/:id',
    ManagerStats: '/manager-stats',
  },

  Payments: {
    Base: '/api/payments',
    Order: '/order',
    TicketOrder: '/ticket-order',
    Verify: '/verify',
    PriceBreakdown: '/price-breakdown',
    MyBookings: '/my-bookings',
    ManagerBookings: '/manager-bookings',
    SubscriptionOrder: '/subscription-order',
    VerifySubscription: '/verify-subscription',
    WalletPay: '/wallet-pay',
    WalletHistory: '/wallet-history',
  },
  Plans: {
    Base: '/api/plans',
    CreatePlans: '/createplans',
    GetPlans: '/getplans',
    UpdatePlan: '/updateplan/:id',
  },
  Bookings: {
    Base: '/api/bookings',
    LockSeats: '/lock-seats',
    PaymentIntent: '/payment-intent',
    Confirm: '/confirm',
    Failed: '/failed',
  },
} as const;
