import { useAppSelector } from '../../redux/hook';
import { useAdminDashboardStats } from '../../hooks/useAdmin';

const AdminDashboard = () => {
  const user = useAppSelector((state) => state.auth.user);
  const { data, isLoading } = useAdminDashboardStats();

  const statsData = data?.stats || {
    totalUsers: 0,
    activeEvents: 0,
    eventManagers: 0,
    commissionRevenue: 0,
    subscriptionRevenue: 0,
    publishingRevenue: 0,
    totalRevenue: 0,
  };

  const platformOverviewStats = [
    { title: 'Total Users', value: String(statsData.totalUsers), icon: '👥', trend: '+0%' },
    { title: 'Active Events', value: String(statsData.activeEvents), icon: '📅', trend: '+0%' },
    { title: 'Event Managers', value: String(statsData.eventManagers), icon: '👔', trend: '+0%' },
  ];

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-full min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-emerald-500"></div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in-up">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-white tracking-tight">
          Admin <span className="text-emerald-400">Dashboard</span>
          <p className="text-sm font-normal text-slate-500 mt-1">{user?.email}</p>
        </h1>
        <p className="text-slate-400 mt-2">
          Overview of Occasio platform statistics, metrics and activities.
        </p>
      </div>

      {/* Platform Metrics Section */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold text-slate-300 flex items-center gap-2">
          <span>📈</span> Platform Overview
        </h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
        {platformOverviewStats.map((stat, i) => (
          <div
            key={i}
            className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-2xl p-6 shadow-xl hover:border-emerald-500/30 transition-all duration-300 group"
          >
            <div className="flex justify-between items-start mb-4">
              <div className="p-3 bg-emerald-500/10 rounded-xl text-xl border border-emerald-500/20 group-hover:scale-110 transition-transform">
                {stat.icon}
              </div>
              <span className="text-emerald-400 text-sm font-semibold flex items-center bg-emerald-500/10 px-2 py-1 rounded-lg border border-emerald-500/20">
                <svg className="w-3 h-3 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={3}
                    d="M5 10l7-7m0 0l7 7m-7-7v18"
                  />
                </svg>
                {stat.trend}
              </span>
            </div>
            <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-1">
              {stat.title}
            </h3>
            <p className="text-3xl font-bold text-white">{stat.value}</p>
          </div>
        ))}
      </div>

      {/* Revenue Section */}
      <div className="mb-6">
        <h2 className="text-lg font-semibold text-slate-300 flex items-center gap-2">
          <span>💰</span> Financial Breakdown
        </h2>
        <p className="text-slate-500 text-xs mt-1">
          Detailed overview of the platform revenue streams generated by event manager subscriptions, publishing fees, and booking commissions.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        {/* Total Revenue Card (Highly Emphasized) */}
        <div className="bg-gradient-to-br from-emerald-950/40 to-slate-900/40 backdrop-blur-xl border border-emerald-500/40 rounded-2xl p-6 shadow-xl shadow-emerald-950/5 hover:border-emerald-400 transition-all duration-300 group relative overflow-hidden">
          <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/10 rounded-full blur-2xl -mr-6 -mt-6"></div>
          <div className="flex justify-between items-start mb-4 relative z-10">
            <div className="p-3 bg-emerald-500/20 rounded-xl text-xl border border-emerald-500/30 text-emerald-400 group-hover:scale-110 transition-transform">
              💰
            </div>
            <span className="text-emerald-400 text-xs font-semibold bg-emerald-500/10 px-2 py-1 rounded-lg border border-emerald-500/20 uppercase tracking-wider">
              Total Earnings
            </span>
          </div>
          <h3 className="text-slate-300 text-sm font-semibold uppercase tracking-wider mb-1 relative z-10">
            Total Revenue
          </h3>
          <p className="text-4xl font-extrabold text-white relative z-10">₹{statsData.totalRevenue}</p>
          <p className="text-xs text-emerald-400/80 mt-2 relative z-10">All platform streams combined</p>
        </div>

        {/* Subscription Revenue Card */}
        <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-2xl p-6 shadow-xl hover:border-indigo-500/30 transition-all duration-300 group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-indigo-500/10 rounded-xl text-xl border border-indigo-500/20 text-indigo-400 group-hover:scale-110 transition-transform">
              💎
            </div>
            <span className="text-indigo-400 text-xs font-semibold bg-indigo-500/10 px-2 py-1 rounded-lg border border-indigo-500/20 uppercase tracking-wider">
              Subscription
            </span>
          </div>
          <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-1">
            Subscription Plans
          </h3>
          <p className="text-3xl font-bold text-white">₹{statsData.subscriptionRevenue}</p>
          <p className="text-xs text-slate-500 mt-2">Paid by managers for upgrade plans</p>
        </div>

        {/* Publishing Revenue Card */}
        <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-2xl p-6 shadow-xl hover:border-amber-500/30 transition-all duration-300 group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-amber-500/10 rounded-xl text-xl border border-amber-500/20 text-amber-400 group-hover:scale-110 transition-transform">
              🚀
            </div>
            <span className="text-amber-400 text-xs font-semibold bg-amber-500/10 px-2 py-1 rounded-lg border border-amber-500/20 uppercase tracking-wider">
              Publish Fee
            </span>
          </div>
          <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-1">
            Event Publishing
          </h3>
          <p className="text-3xl font-bold text-white">₹{statsData.publishingRevenue}</p>
          <p className="text-xs text-slate-500 mt-2">Flat ₹99 paid per event published</p>
        </div>

        {/* Booking Commissions Card */}
        <div className="bg-slate-900/40 backdrop-blur-xl border border-slate-800/60 rounded-2xl p-6 shadow-xl hover:border-sky-500/30 transition-all duration-300 group">
          <div className="flex justify-between items-start mb-4">
            <div className="p-3 bg-sky-500/10 rounded-xl text-xl border border-sky-500/20 text-sky-400 group-hover:scale-110 transition-transform">
              📈
            </div>
            <span className="text-sky-400 text-xs font-semibold bg-sky-500/10 px-2 py-1 rounded-lg border border-sky-500/20 uppercase tracking-wider">
              Commissions
            </span>
          </div>
          <h3 className="text-slate-400 text-sm font-semibold uppercase tracking-wider mb-1">
            Ticket Commissions
          </h3>
          <p className="text-3xl font-bold text-white">₹{statsData.commissionRevenue}</p>
          <p className="text-xs text-slate-500 mt-2">Platform booking fee commission share</p>
        </div>
      </div>
    </div>
  );
};

export default AdminDashboard;
